packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@vshulcz/deja-vu-darwin-amd64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu-darwin-arm64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu-linux-amd64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu-linux-arm64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu-windows-amd64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu-windows-arm64@0.19.4 || 0.19.5 || 0.20.0'
  - '@vshulcz/deja-vu@0.19.4 || 0.19.5 || 0.20.0'
