packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/2da384479705b9bd70a1659f78c93608c94b3001: set this to true or false
