packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@univerjs-pro/engine-formula-rust-binding-darwin-arm64@1.0.0-insiders.20260829-2e3c387'
  - '@univerjs-pro/engine-formula-rust-binding-linux-arm64-gnu@1.0.0-insiders.20260829-2e3c387'
  - '@univerjs-pro/engine-formula-rust-binding-linux-x64-gnu@1.0.0-insiders.20260829-2e3c387'
  - '@univerjs-pro/engine-formula-rust-binding-win32-x64-msvc@1.0.0-insiders.20260829-2e3c387'
  - '@univerjs-pro/engine-formula-rust-binding@1.0.0-insiders.20260829-2e3c387'
  - '@univerjs-pro/exchange-node-binding-darwin-arm64@0.1.1'
  - '@univerjs-pro/exchange-node-binding-linux-arm64-gnu@0.1.1'
  - '@univerjs-pro/exchange-node-binding-linux-x64-gnu@0.1.1'
  - '@univerjs-pro/exchange-node-binding-win32-x64-msvc@0.1.1'
  - '@univerjs-pro/exchange-node-binding@0.1.1'
