import { categoryLabel, CATEGORIES } from './constants.js';

function truncate(text, max) {
  if (!text) return '';
  const clean = text.replace(/\s+/g, ' ').trim();
  return clean.length > max ? `${clean.slice(0, max - 1)}…` : clean;
}

function mdCell(text) {
  return (text || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

export function registryStats(registry, meta) {
  const perCategory = new Map();
  for (const e of registry) {
    const primary = e.categories[0];
    perCategory.set(primary, (perCategory.get(primary) || 0) + 1);
  }
  return {
    total: registry.length,
    monitored: meta.monitoredRepos,
    totalStars: meta.totalStars,
    perCategory,
  };
}

export function renderReadme(registry, meta, template, lang) {
  const s = registryStats(registry, meta);
  const date = meta.generatedAt.slice(0, 10);
  const badge = `https://img.shields.io/badge/last%20updated-${date.replace(/-/g, '--')}-orange`;
  const categoryLine = CATEGORIES.filter((c) => s.perCategory.has(c.id))
    .map((c) => `${c[lang]} ${s.perCategory.get(c.id)}`)
    .join(' · ');
  const top10Rows = [...registry]
    .sort((a, b) => b.stars - a.stars)
    .slice(0, 10)
    .map(
      (e, i) =>
        `| ${i + 1} | [${mdCell(e.repo)}](${e.url}) | ${e.stars.toLocaleString()} | ${categoryLabel(e.categories[0], lang)} | ${mdCell(truncate(e.description, 60))} |`,
    )
    .join('\n');
  return template
    .replaceAll('{{UPDATED_BADGE}}', badge)
    .replaceAll('{{TOTAL}}', s.total)
    .replaceAll('{{MONITORED}}', s.monitored)
    .replaceAll('{{SUM_STARS}}', s.totalStars.toLocaleString())
    .replaceAll('{{LAST_UPDATED}}', meta.generatedAt.replace('T', ' ').replace('Z', ' UTC'))
    .replaceAll('{{CATEGORY_COUNTS}}', categoryLine)
    .replaceAll('{{TOP10_TABLE}}', top10Rows);
}

export function renderCatalog(registry, meta, lang) {
  const lines = [];
  const heading = lang === 'zh' ? 'DSH 插件目录（中文）' : 'DSH Plugin Catalog (English)';
  const intro =
    lang === 'zh'
      ? `收录 **${registry.length}** 个插件 · 更新于 ${meta.generatedAt} · 收录不代表兼容性或安全认证。`
      : `**${registry.length}** plugins · updated ${meta.generatedAt} · Listing does not imply compatibility or security.`;
  lines.push(`# ${heading}\n`);
  lines.push(`> ${intro}\n`);
  lines.push('## 分类 / Categories\n');
  for (const c of CATEGORIES) {
    const count = registry.filter((e) => e.categories.includes(c.id)).length;
    if (count > 0) lines.push(`- [${c[lang]} (${count})](#${c.id})`);
  }
  lines.push('');
  for (const c of CATEGORIES) {
    const items = registry
      .filter((e) => e.categories.includes(c.id))
      .sort((a, b) => b.stars - a.stars);
    if (items.length === 0) continue;
    lines.push(`## ${c[lang]} (${items.length})\n`);
    lines.push(
      lang === 'zh'
        ? '| 插件 | Stars | 许可证 | 说明 | 安装命令 |'
        : '| Plugin | Stars | License | Description | Install |',
    );
    lines.push('| --- | ---: | --- | --- | --- |');
    for (const e of items) {
      lines.push(
        `| [${mdCell(e.repo)}](${e.url}) | ${e.stars.toLocaleString()} | ${mdCell(e.license)} | ${mdCell(truncate(e.description, 70))} | \`${e.installCommand}\` |`,
      );
    }
    lines.push('');
  }
  lines.push('---');
  lines.push(
    lang === 'zh'
      ? '由 `npm run generate` 自动生成，请勿手工编辑。'
      : 'Auto-generated by `npm run generate`; do not edit by hand.',
  );
  lines.push('');
  return lines.join('\n');
}
