packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@zseven-w/dsh-openpencil-darwin-arm64@0.1.0-rc.7'
  - '@zseven-w/dsh-openpencil-darwin-x64@0.1.0-rc.7'
  - '@zseven-w/dsh-openpencil-linux-arm64@0.1.0-rc.7'
  - '@zseven-w/dsh-openpencil-linux-x64@0.1.0-rc.7'
  - '@zseven-w/dsh-openpencil-win32-arm64@0.1.0-rc.7'
  - '@zseven-w/dsh-openpencil-win32-x64@0.1.0-rc.7'
