import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { categoryLabel, CATEGORIES } from './lib/constants.js';
import { applyOverrides, loadOverrides } from './lib/overrides.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REGISTRY_FILE = path.join(ROOT, 'registry', 'plugins.json');
const META_FILE = path.join(ROOT, 'registry', 'meta.json');
const TEMPLATE_FILE = path.join(ROOT, 'data', 'readme.template.md');

function truncate(text, max) {
  if (!text) return '';
  const clean = text.replace(/\s+/g, ' ').trim();
  return clean.length > max ? `${clean.slice(0, max - 1)}…` : clean;
}

function mdCell(text) {
  return (text || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function stats(registry, meta) {
  const perCategory = new Map();
  for (const e of registry) {
    const primary = e.categories[0];
    perCategory.set(primary, (perCategory.get(primary) || 0) + 1);
  }
  return {
    total: registry.length,
    monitored: meta.monitoredRepos,
    totalStars: meta.totalStars,
    perCategory,
  };
}

function renderReadme(registry, meta, template) {
  const s = stats(registry, meta);
  const date = meta.generatedAt.slice(0, 10);
  const badge = `https://img.shields.io/badge/last%20updated-${date.replace(/-/g, '--')}-orange`;
  const categoryLine = CATEGORIES.filter((c) => s.perCategory.has(c.id))
    .map((c) => `${c.zh} ${s.perCategory.get(c.id)}`)
    .join(' · ');
  const top10 = [...registry]
    .sort((a, b) => b.stars - a.stars)
    .slice(0, 10);
  const top10Rows = top10
    .map(
      (e, i) =>
        `| ${i + 1} | [${mdCell(e.repo)}](${e.url}) | ${e.stars.toLocaleString()} | ${categoryLabel(e.categories[0], 'zh')} | ${mdCell(truncate(e.description, 60))} |`,
    )
    .join('\n');
  return template
    .replaceAll('{{UPDATED_BADGE}}', badge)
    .replaceAll('{{TOTAL}}', s.total)
    .replaceAll('{{MONITORED}}', s.monitored)
    .replaceAll('{{SUM_STARS}}', s.totalStars.toLocaleString())
    .replaceAll('{{LAST_UPDATED}}', meta.generatedAt.replace('T', ' ').replace('Z', ' UTC'))
    .replaceAll('{{CATEGORY_COUNTS}}', categoryLine)
    .replaceAll('{{TOP10_TABLE}}', top10Rows);
}

function renderCatalog(registry, meta, lang) {
  const lines = [];
  const heading = lang === 'zh' ? 'DSH 插件目录（中文）' : 'DSH Plugin Catalog (English)';
  const intro =
    lang === 'zh'
      ? `收录 **${registry.length}** 个插件 · 更新于 ${meta.generatedAt} · 收录不代表兼容性或安全认证。`
      : `**${registry.length}** plugins · updated ${meta.generatedAt} · Listing does not imply compatibility or security.`;
  lines.push(`# ${heading}\n`);
  lines.push(`> ${intro}\n`);
  lines.push('## 分类 / Categories\n');
  for (const c of CATEGORIES) {
    const count = registry.filter((e) => e.categories.includes(c.id)).length;
    if (count > 0) lines.push(`- [${c[lang]} (${count})](#${c.id})`);
  }
  lines.push('');
  for (const c of CATEGORIES) {
    const items = registry
      .filter((e) => e.categories.includes(c.id))
      .sort((a, b) => b.stars - a.stars);
    if (items.length === 0) continue;
    lines.push(`## ${c[lang]} (${items.length})\n`);
    lines.push(
      lang === 'zh'
        ? '| 插件 | Stars | 许可证 | 说明 | 安装命令 |'
        : '| Plugin | Stars | License | Description | Install |',
    );
    lines.push('| --- | ---: | --- | --- | --- |');
    for (const e of items) {
      lines.push(
        `| [${mdCell(e.repo)}](${e.url}) | ${e.stars.toLocaleString()} | ${mdCell(e.license)} | ${mdCell(truncate(e.description, 70))} | \`${e.installCommand}\` |`,
      );
    }
    lines.push('');
  }
  lines.push('---');
  lines.push(
    lang === 'zh'
      ? '由 `npm run generate` 自动生成，请勿手工编辑。'
      : 'Auto-generated by `npm run generate`; do not edit by hand.',
  );
  lines.push('');
  return lines.join('\n');
}

function main() {
  // Re-apply manual overrides so curation edits take effect without re-fetching.
  const registry = applyOverrides(
    JSON.parse(fs.readFileSync(REGISTRY_FILE, 'utf8')),
    loadOverrides(ROOT),
  ).sort((a, b) => b.stars - a.stars);
  const meta = JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
  meta.pluginCount = registry.length;
  meta.totalStars = registry.reduce((acc, e) => acc + e.stars, 0);

  fs.writeFileSync(REGISTRY_FILE, `${JSON.stringify(registry, null, 2)}\n`);
  fs.writeFileSync(META_FILE, `${JSON.stringify(meta, null, 2)}\n`);

  const template = fs.readFileSync(TEMPLATE_FILE, 'utf8');

  fs.writeFileSync(path.join(ROOT, 'README.md'), renderReadme(registry, meta, template));
  fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'docs', 'catalog.zh.md'), renderCatalog(registry, meta, 'zh'));
  fs.writeFileSync(path.join(ROOT, 'docs', 'catalog.en.md'), renderCatalog(registry, meta, 'en'));

  fs.mkdirSync(path.join(ROOT, 'site'), { recursive: true });
  fs.copyFileSync(REGISTRY_FILE, path.join(ROOT, 'site', 'plugins.json'));

  const s = stats(registry, meta);
  console.log(`dsh-hub: generated README.md, docs/catalog.{zh,en}.md, site/plugins.json`);
  console.log(`  plugins=${s.total} monitored=${s.monitored} totalStars=${s.totalStars}`);
}

main();
