packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/4bbd2dbeee1f370e4da71a42670a98d957eab6a4: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/f1feb66b0cbba780c23787f6baefb3da2f56895b: set this to true or false
