packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/cf8c47735c11535fe88d67f6402d1935a7dcd813: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/f1feb66b0cbba780c23787f6baefb3da2f56895b: set this to true or false
