packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  tydora@https://codeload.github.com/zuorn/Tydora/tar.gz/1a338f33d350b77980d59d84aa186b4c9eb68a6f: set this to true or false
