packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  cloudflared: set this to true or false
  cpu-features: set this to true or false
  node-pty: set this to true or false
  ssh2: set this to true or false
